<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Helper\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\workers\WinPool.TestWorker\WinPool.TestWorker.csproj" />
    <ProjectReference Include="..\..\src\WinPool.Testing.Tools\WinPool.Testing.Tools.csproj" />
    <ProjectReference Include="Helper\WinPool.TestWorker.ProcessHelper.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
