<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationIcon>..\WinPool.App\Assets\CAppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinPool.Application\WinPool.Application.csproj" />
    <ProjectReference Include="..\WinPool.Infrastructure.Sqlite\WinPool.Infrastructure.Sqlite.csproj" />
    <ProjectReference Include="..\WinPool.Infrastructure.Windows\WinPool.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\WinPool.Ipc\WinPool.Ipc.csproj" />
    <ProjectReference Include="..\WinPool.Inventory\WinPool.Inventory.csproj" />
    <ProjectReference Include="..\WinPool.Monitoring\WinPool.Monitoring.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\WinPool.App\Assets\CAppIcon.ico" Link="Assets\CAppIcon.ico" />
  </ItemGroup>
</Project>
